# usage:
# ansible-playbook change-userpassword.yaml --extra-vars '{"host":"MYHOST", "password":"mypass", "user":"root"}'

---
- hosts: '{{ host }}'
  become: yes
  become_user: root
  gather_facts: no

  tasks:

    - name: Generate Encrypted Password
      command:  mkpasswd -m sha-512 '{{ password }}'
      register: encrypted_password
      connection: local


    - debug:
      msg: " Encrypted_pass --- {{ encrypted_password.stdout }}  password --- '{{ password }}'"

    - name: Updating user '{{ user }}'
      user:
        name: '{{ user }}'
        password: '{{ encrypted_password.stdout }}'
        state: present

